### ISSUE TITLE
Looks very good. Any chance I could skip using Boost?

### ISSUE THREAD

**Issue by DumboJet** [eteran/cpp-json#3]
The interface looks very good. :)
Any chance I could skip using Boost?

I am searching the web all day today and I don't understand why on earth there is not a single easy to use library that does not depend on some secondary gigantic project.
:(

**Comment by DumboJet** [comment]
OK. I have downloaded boost and it seems working nice! :)
One suggestion :) :
I think it would be easier to locate all the conversion functions like `to_number` if you added them all inside a class with static members like:

JsonConverter::to_number(val);

I would prefer sth like this:

JsonConverter::ToNumber(val);

...but I guess that's not the coding style of the project. :)

**Comment by eteran** [comment]
boost is required for a SINGLE part `boost::variant`, this is essentially a "better union", which allows the included types to be non-POD. C++11 has made unions more flexible and may be able to handle this nicely, so I am considering reworking the code. But it will be a bit of work since it's a completely different approach.

Regarding your second comment. All of the methods are available in the `json` namespace, found in `json.h`. So you can just write:

    json::to_number(val)

Personally, I like to use ADL when I can, so I often leave out the `json::` part in examples, but feel free to use the fully qualified name if it makes it more clear :-)

**Comment by eteran** [comment]
Just as a follow up. You've inspired me, it took a bit of effort, but cpp-json no longer depends on boost at all :-). Just a decent c++11 compiler. Incidentally, the manual solution is slightly more space efficient too! `sizeof(json::value)` went down to `24` from `32`

**Comment by DumboJet** [comment]
Nice! :)
Thanks. :)
